---
- name: Create role app directory for search_head
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/apps/role_search_head/local"
    state: directory
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0755'

- name: Deploy search head server.conf stanza
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ splunk_home }}/etc/apps/role_search_head/local/server.conf"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0600'
  notify: Restart splunk

- name: Deploy search head web.conf
  ansible.builtin.template:
    src: web.conf.j2
    dest: "{{ splunk_home }}/etc/apps/role_search_head/local/web.conf"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0600'
  notify: Restart splunk
