---
- name: Assert required search head variables are defined
  ansible.builtin.import_tasks: assert.yml
  tags: [always, assert]

- name: Deploy search head configuration
  ansible.builtin.import_tasks: configure.yml
  tags: [search_head, configure]

- name: Flush handlers to restart Splunk if config changed
  ansible.builtin.meta: flush_handlers
  tags: [search_head, configure]

- name: Wait for Search Head to be ready
  ansible.builtin.import_tasks: wait.yml
  tags: [search_head, wait]
