---
- name: Wait for SH management port to open after restart
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 8089
    timeout: 120
    state: started

- name: Poll SH cluster status until connected to CM
  ansible.builtin.uri:
    url: "{{ splunk_api_scheme }}://{{ ansible_host }}:8089\
          /services/cluster/searchhead/searchheadconfig"
    method: GET
    user: "{{ splunk_admin_username }}"
    password: "{{ splunk_admin_password }}"
    validate_certs: false
    status_code: 200
    return_content: true
  register: sh_cluster_info
  until: sh_cluster_info.status == 200
  retries: "{{ splunk_sh_readiness_retries }}"
  delay: "{{ splunk_sh_readiness_delay }}"
  failed_when: sh_cluster_info.status not in [200]
