---
- name: Create role app directory for cluster_manager
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/apps/role_cluster_manager/local"
    state: directory
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0755'

- name: Deploy cluster manager server.conf stanza
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ splunk_home }}/etc/apps/role_cluster_manager/local/server.conf"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0600'
  notify: Restart splunk

- name: Flush Handlers to avoid race conditions
  ansible.builtin.meta: flush_handlers
