---
- name: Set open file descriptor limits for splunk user
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{ splunk_ulimit_open_files }}"
    dest: /etc/security/limits.d/99-splunk.conf
  loop:
    - soft
    - hard

- name: Set max process limits for splunk user
  community.general.pam_limits:
    domain: "{{ splunk_user }}"
    limit_type: "{{ item }}"
    limit_item: nproc
    value: "{{ splunk_ulimit_max_procs }}"
    dest: /etc/security/limits.d/99-splunk.conf
  loop:
    - soft
    - hard
