---
- name: Restart splunk
  become: true
  ansible.builtin.command:
    cmd: "/opt/splunk/bin/splunk restart"

- name: Invoke cluster bundle
  become: true
  become_user: "{{ splunk_user }}"
  ansible.builtin.command:
    cmd: "/opt/splunk/bin/splunk apply cluster-bundle --answer-yes --accept-license -auth {{ splunk_admin_username }}:{{ splunk_admin_password }}"

