---
- name: Create role app directory for indexer
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/manager-apps/local/_cluster"
    state: directory
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0755'

- name: Deploy indexer inputs.conf (forwarder receiving port)
  ansible.builtin.template:
    src: inputs.conf.j2
    dest: "{{ splunk_home }}/etc/manager-apps/_cluster/local/inputs.conf"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0600'
  notify: Invoke cluster bundle
