---
- name: Create role app directory for indexer
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/apps/role_indexer/local"
    state: directory
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0755'

- name: Deploy indexer peer server.conf stanza
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ splunk_home }}/etc/apps/role_indexer/local/server.conf"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: '0600'
  notify: Restart splunk
